# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

variables:
  uiSource: "/src"
  uiBuild: "$(uiSource)/build"

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'cv'
      organization: 'gerardito'
      scannerMode: 'CLI'
      configMode: manual
      cliProjectKey: 'cv-gerardito'
      cliProjectName: 'react-cv'
      extraProperties: |
        # Additional properties that will be passed to the scanner, 
        # Put one key=value per line, example:
        sonar.exclusions=**/*.stories.js,**/*.spec.js,**/*.spec.ts, **/*.spec.tsx, **/index.ts, **/index.js,scripts/**,coverage/**,**/node_modules/**,**/dist/**,**/__mocks__/**,examples/**,jest.config.js,packages/vanilla/**
        sonar.javascript.lcov.reportPaths=coverage/lcov.info
        sonar.sourceEncoding=UTF-8
        sonar.verbose=true
        sonar.host.url=https://sonarcloud.io
        sonar.cfamily.build-wrapper-output.bypass=true
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], 'False'))



  - script: |
        pushd $(uiSource)
        npm install
        npm run build
    displayName: "Build Aplication"
      
  - task: SonarCloudPublish@1
    displayName: 'Run Code Analysis'
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], 'False'))


  - task: SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], 'False'))
